#!/bin/bash
set -e

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$( cd "$( dirname "$SCRIPT_PATH" )" && pwd )"
source "$SCRIPT_DIR/.venv/bin/activate"
python3 "$SCRIPT_DIR/scripts/zwanski-oauth-mapper.py" "$@"
